export const EXPENSE_CATEGORIES = [
  "Vivienda & Alquiler",
  "Supermercado & Alimentación",
  "Restaurantes & Bares",
  "Servicios Públicos (Luz/Agua/Gas)",
  "Telefonía & Internet",
  "Gasolina & Combustible",
  "Transporte Público & Taxi",
  "Salud & Farmacia",
  "Seguros & Pólizas",
  "Gimnasio & Deporte",
  "Ropa & Calzado",
  "Cuidado Personal & Barbería",
  "Educación & Cursos",
  "Entretenimiento & Cine",
  "Suscripciones Digitales",
  "Viajes & Vacaciones",
  "Mascotas & Veterinario",
  "Tecnología & Gadgets",
  "Mantenimiento del Hogar",
  "Regalos & Celebraciones",
  "Impuestos & Tasas",
  "Imprevistos & Emergencias",
  "Inversiones",
  "Ahorro Programado",
  "Otros Gastos",
] as const;

export const INCOME_CATEGORIES = [
  "Salario / Nómina Principal",
  "Horas Extras & Guardias",
  "Bonificaciones & Comisiones",
  "Servicios Freelance",
  "Consultoría & Asesoría",
  "Negocio Propio / Ventas",
  "Dividendos & Acciones",
  "Rentas / Alquileres de Inmuebles",
  "Rendimientos & Intereses Bancarios",
  "Reembolsos & Devoluciones",
  "Venta de Artículos de Segunda Mano",
  "Premios & Sorteos",
  "Regalos & Ayudas Familiares",
  "Criptomonedas & Staking",
  "Otros Ingresos",
] as const;
